
build: 
  commands: 
    - "make deps"
    - "make build-linux"
  image: "mnbbrown/ci:latest"

publish: 
  docker: 
    email: "me@matthewbrown.io"
    password: $$DOCKER_HUB_PASSWORD
    repo: mnbbrown/csv2api
    storage_driver: overlay
    tag: 
      - $$COMMIT
      - latest
    username: mnbbrown