debug: true

build:
    image: mnbbrown/ci:latest
    commands: 
        - make deps
        - make test
        - make build-linux

publish:
  docker:
    username: mnbbrown
    password: $$DOCKER_HUB_PASSWORD
    email: "me@matthewbrown.io"
    repo: mnbbrown/csv2api
    tag: latest
    file: Dockerfile