debug: true

build: 
    commands: 
        - "make deps"
        - "make test"
        - "make build-linux"
    image: "mnbbrown/ci:latest"

publish:
    docker:
        registry: registry.matthewbrown.io
        repo: mnbbrown/csv2api
        tag:
            - $$COMMIT
            - latest
        storage_driver: overlay