
build: 
  commands: 
    - "make deps"
    - "make test"
    - "make build-linux"
  image: "mnbbrown/ci:latest"

publish:
  docker:
    repo: mnbbrown/csv2api
    username: mnbbrown
    email: "me@matthewbrown.io"
    password: $$DOCKER_HUB_PASSWORD
    tag: 
      - $$COMMIT
      - latest
    storage_driver: overlay