debug: true

build:
    image: mnbbrown/ci:latest
    environment:
        - GOOS=linux
        - GOARCH=amd64
        - CGO_ENABLED=0
    commands:
        - make deps
        - make test
        - make build

publish:
    docker:
        username: "mnbbrown"
        password: "$$DOCKER_HUB_PASSWORD"
        email: "$$DOCKER_HUB_EMAIL"
        repo: "mnbbrown/csv2api"
        tag:
            - $$COMMIT
            - latest
        storage_driver: overlay
        when:
            branch: master
    docker:
        username: "mnbbrown"
        password: "$$DOCKER_HUB_PASSWORD"
        email: "$$DOCKER_HUB_EMAIL"
        repo: "mnbbrown/csv2api"
        tag:
            - $$COMMIT
            - develop
        storage_driver: overlay
        when:
            branch: develop
